#!/bin/sh
#             __ _                           _
#  _ __ ___  / _(_)      _ __   ___  _ __ __| |_   ___ __  _ __
# | '__/ _ \| |_| |_____| '_ \ / _ \| '__/ _` \ \ / / '_ \| '_ \
# | | | (_) |  _| |_____| | | | (_) | | | (_| |\ V /| |_) | | | |
# |_|  \___/|_| |_|     |_| |_|\___/|_|  \__,_| \_/ | .__/|_| |_|
#                                                   |_|

# any failure in piped commands aborts pipe
set -o pipefail
# exit when any command fails
set -e

function echoexit() {
    # Print to stderr and exit
    printf "$@" 1>&2
    exit 1
}

# Checking dependencies:
whereis nordvpn > /dev/null || echoexit "'nordvpn' not found."

function menu() {
    # Menu command, should read from stdin and write to stdout.

    rofi -dmenu -p "Select"
}

function usage() {
    printf "Dynamic menu interface for nordvpn.

Usage:
  rofi-nordvpn [-h] [-s LABEL]
    -h                                 Display this help message.
    -s                                 Display current vpn status, useful for status bars.
      LABEL                            Prefix label for the status information."
}

function init_menu() {
    # Initial menu.

    local choices="connect\ndisconnect\ninfo"
    printf "$choices" | menu
}

function connect() {
    # nordvpn connect options.

    local choices="default\ncountries\ncities\np2p"
    printf "$choices" | menu
}

function countries() {
    # Country selection.

    local choices="$(nordvpn countries | tr -d '\r,-' | tr -s "[:blank:]" "\n" | sed '/^\s*$/d' | sort)"
    printf "$choices" | menu
}

function cities() {
    # City selection.

    local choices="$(nordvpn cities $1 | tr -d '\r,-' | tr -s "[:blank:]" "\n" | sed '/^\s*$/d' | sort)"
    printf "$choices" | menu
}

function disconnect() {
    # disconnect

    nordvpn disconnect
}

function status() {
    # Echo the status.

    local status="$(nordvpn status | tr -d '\r -')"
    if [[ "$status" != *"Connected"* ]]; then
        printf "$STATUS_LABEL Off"
    else
        printf "$STATUS_LABEL $(printf "$status" | grep "City" | cut -d ":" -f 2)"
    fi
}

function info() {
    # Show vpn info.

    local choices="$(nordvpn status | tr -d '\r-' | sed 's/^ *//')"
    printf "$choices" | menu
}

# Parse options to the `rofi-nordvpn` command
while getopts ":hs" opt; do
    case ${opt} in
        h )
            usage
            exit 0
            ;;
        s )
            STATUS_LABEL="$2"
            status
            exit 0
            ;;
        \? )
            printf "Invalid Option: -$OPTARG" 1>&2
            usage
            exit 1
            ;;
    esac
done

case "$(init_menu)" in
    "connect")
        case $(connect) in
            "default")
                nordvpn connect
                ;;
            "countries")
                country="$(countries)"
                [ -n "$country" ] && nordvpn connect "$country"
                ;;
            "cities")
                country="$(countries)"
                [ -n "$country" ] && city="$(cities "$country")"
                [ -n $city ] && nordvpn connect "$country" "$city"
                ;;
            "p2p")
                nordvpn connect p2p
                ;;
            *)
                ;;
        esac
        ;;
    "disconnect")
        disconnect
        ;;
    "info")
        info
        ;;
    *)
        ;;
esac
